<!-- <div id="Prices" class="container">
  <h2>Prices</h2>
  <div class="grid">
    <PriceCard title="Personal" price="50" features={["1-2 Pages"]} />
    <PriceCard
      title="Small business"
      price="100"
      features={["3-5 Pages", "Monthly analytics", "Contact form"]}
    />
    <PriceCard
      title="Enterprise"
      price="300"
      features={[
        "6+ Pages",
        "Monthly analytics",
        "Contact form",
        "User analysis",
      ]}
    />
    <PriceCard
      custom={true}
      title="Take away"
      features={[
        "Bespoke, mobile optimised solution for self hosting. All files will be packaged up and provided ready to be dropped into your own hosting solution.",
      ]}
    />
  </div>
  <div class="cta">
    <Button content="Get in touch" linkUrl="#Footer" />
  </div>
</div> -->
<!-- --------------- -->